### ISSUE TITLE
Backend Technologies Discussion 

### ISSUE THREAD

**Issue by germangamboa95** [ProjectCodex/QuizzyBackend#1]
# Team, welcome to Quizzy! 

The hottest tech startup that is about to disrupt the quizzing market. 

The first thing we need to focus on as a backend team is the tech that we be using. 
Rather than just say let's go with Node, Go or PHP I want us to consider a few things. 

- What skills does the overall team have. 
- What are valid use cases for the tech and what are its downsides. 
- Lastly what do you want to get out of this project. 

Feel free to propose any tech that you feel is valid for this project.

**Comment by jcadiente505** [comment]
personally I have a PHP backend internship right now so having a project outside of the job, would be cool for me and hammer in those fundamentals and concepts

**Comment by jcadiente505** [comment]
But I also have Node experience from personal projects and camp so I can go either way

**Comment by germangamboa95** [comment]
@jcadiente505 How comfortable are you with laravel?

**Comment by jcadiente505** [comment]
Pretty comfortable, if we’re talking a junior level, crud ops, Writing API’s etc

**Comment by jcadiente505** [comment]
It’s kinda hard for me to tell cause they’re is a lot of out of the box magic with laravel

**Comment by germangamboa95** [comment]
There is a lot of magic which is good and bad in my opinion. Its good if you want to get up and running super fast and bad if you actually want to learn about how things work. Depending on what you guys want to get out of this going with "up and running fast" would be more of a laravel choice while writing it in node or symphony would be more of a learning the internals choice.

**Comment by jcadiente505** [comment]
Then I would rather Symfony

**Comment by jcadiente505** [comment]
But it’s whatever Kevin and victor want too

**Comment by germangamboa95** [comment]
@BarkRanger @victor-riv  What do you guys think. So far Symphony has been brought forward as a possibility.

**Comment by victor-riv** [comment]
I would strongly prefer either Node with Express or Laravel. I have some experience with express and Laravel I don't know it but it's what devs at my job use so I would be interested in that.

**Comment by victor-riv** [comment]
But ultimately it's w.e we decide

**Comment by jcadiente505** [comment]
Then lets do Node, I like Laravel but it is ALOT of magic happening and the goal of this project is to strengthen knowledge right?

**Comment by victor-riv** [comment]
I agree plus you can’t go wrong with Node and practicing good ole JavaScript

**Comment by germangamboa95** [comment]
Cool now we just have to hear from @BarkRanger. I'm guessing we want to go with node and express? And are you guys more familiar mongo or express?

**Comment by jcadiente505** [comment]
Im very comfortable in MERN stack so that’ll be fine

**Comment by BarkRanger** [comment]
I'm the grunt of the group. You guys should make these decisions.

**Comment by germangamboa95** [comment]
@BarkRanger We are all grunts :D lol Okay so I guess we will go with some server side JS. Now my question to you guys is what parts of of doing backend are you interested in? It can be different for everyone. Like for example someone could be more interested in learning how requests come in and handling headers properly and another could be more interested in the database part and how we will store our data.

**Comment by germangamboa95** [comment]
Alright so we are doing node-express with some mongo as our main database since we want to add some docker into the mix. The initial setup of the project is in the master branch. I'll be updating the README a little later so you guys have more info.
